version: "2"

services:
  jupyter:
    image: ogrisel/distributed:latest
    command: start-notebook.sh
    ports:
       - "8888:8888"
    networks:
      - distributed
    links:
        - dask-scheduler
    container_name: jupyter

  dask-scheduler:
    image: ogrisel/distributed:latest
    ports:
     - "8786:8786"
     - "9786:9786"
     - "8787:8787"
     - "8788:8788"
    command: start-dask-scheduler.sh
    networks:
      - distributed
    container_name: dask-scheduler

  dask-worker:
    ports:
     - "8789:8789"
    image: ogrisel/distributed:latest
    command: start-dask-worker.sh
    networks:
      - distributed
    links:
        - dask-scheduler

networks:
  distributed:
    # Enable multi-host communication
    driver: overlay
    # Single host communication
    #driver: bridge
