apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  labels:
    name: dask-scheduler
    app: distributed
spec:
  ports:
    - port: 8786
      targetPort: 8786
      name: dask-scheduler-tcp
    - port: 9786
      targetPort: 9786
      name: dask-scheduler-http
  selector:
    name: dask-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler-status
  labels:
    name: dask-scheduler-status
    app: distributed
spec:
  type: LoadBalancer
  ports:
    - port: 8787
      targetPort: 8787
      name: dask-scheduler-external-bokeh
    - port: 8788
      targetPort: 8788
      name: dask-scheduler-internal-bokeh
  selector:
    name: dask-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: dask-worker-status
  labels:
    name: dask-worker-status
    app: distributed
spec:
  type: LoadBalancer
  ports:
    - port: 8789
      targetPort: 8789
      name: dask-worker-internal-bokeh
  selector:
    name: dask-worker
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dask-scheduler
    app: distributed
  name: dask-scheduler
spec:
  replicas: 1
  selector:
    name: dask-scheduler
  template:
    metadata:
      labels:
        name: dask-scheduler
    spec:
      containers:
        - name: dask-scheduler
          image: mydistributed2
          args: ["dask-scheduler"]
          ports:
          - name: rpc
            containerPort: 8786
          - name: http
            containerPort: 9786
          - name: bokeh-internal
            containerPort: 8788
          - name: bokeh
            containerPort: 8787
          resources:
            requests: 
              cpu: 500m
              memory: 100Mi
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dask-worker
    app: distributed
  name: dask-worker
spec:
  replicas: 2
  selector:
    name: dask-worker
  template:
    metadata:
      labels:
        name: dask-worker
    spec:
      containers:
        - name: dask-worker
          image: mydistributed2
          args: ["dask-worker", "dask-scheduler:8786"]
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
          workingDir: /work
