apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  labels:
    name: dask-scheduler
spec:
  ports:
    - port: 8786
      targetPort: 8786
      name: dask-scheduler-tcp
    - port: 9786
      targetPort: 9786
      name: dask-scheduler-http
    - port: 8788
      targetPort: 8788
  selector:
    name: dask-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler-status
  labels:
    name: dask-scheduler-status
spec:
  type: LoadBalancer
  ports:
    - port: 8787
      targetPort: 8787
  selector:
    name: dask-scheduler
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dask-scheduler
  name: dask-scheduler
spec:
  replicas: 1
  selector:
    name: dask-scheduler
  template:
    metadata:
      labels:
        name: dask-scheduler
    spec:
      containers:
        - name: dask-scheduler
          image: ogrisel/distributed:latest
          args: ["start-dask-scheduler.sh"]
          ports:
          - name: rpc
            containerPort: 8786
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dask-worker
  name: dask-worker
spec:
  replicas: 3
  selector:
    name: dask-worker
  template:
    metadata:
      labels:
        name: dask-worker
    spec:
      containers:
        - name: dask-worker
          image: ogrisel/distributed:latest
          args: ["start-dask-worker.sh"]
