apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
  labels:
    name: jupyter-notebook
    app: dask
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
      name: jupyter-http
  selector:
    name: jupyter-notebook
---
apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  labels:
    name: dask-scheduler
    app: dask
spec:
  type: LoadBalancer
  ports:
    - port: 8786
      targetPort: 8786
      name: dask-scheduler-tcp
    - port: 9786
      targetPort: 9786
      name: dask-scheduler-http
    - port: 8787
      targetPort: 8787
      name: dask-scheduler-bokeh
  selector:
    name: dask-scheduler
